### ISSUE TITLE
Sometimes AfterAll Hangs

### ISSUE THREAD

**Issue by xjamundx** [paypal/nemo-mocha-factory#2]
```
	after(function (done) {
		_nemo.driver.quit().then(function () {
			done();
		});
	});
```
Sometimes we never make it into the closure that contains `done()` and so we get this error:

```
  1) My Test @my_project_P1@my_project_section@@My Test "after all" hook:
     Uncaught Error: Wait timed out after 5053ms
```

This is possibly more of a support request, so feel free to close if you feel it's on my end on not an actual issue with nemo :smile:

**Comment by johnkchiu** [comment]
This is probably because `_nemo.driver.quit()` probably rejected.  Try adding an additional function to handle the error:

```
    after(function (done) {
        _nemo.driver.quit().then(function () {
            done();
        }, function(err) {
            done(err); 
        });
    });
```
