### ISSUE TITLE
Nemo Handle within Describe Block?

### ISSUE THREAD

**Issue by benmarten** [paypal/nemo-mocha-factory#3]
Hi Matt, following up on our discussion from here: https://github.com/paypal/nemo/issues/19

I need the nemo handle within the describe block, but that does not work atm with the nemoFactory:

    nemoFactory({
        "plugins": plugins,
        "setup": setup
    });
    describe('suite1', function() {
        nemo.driver.get('http://www.google.com/'); // not defined
        console.log(nemo.driver.session_); 
    });

----
ReferenceError: nemo is not defined

Appreciate your help!

UPDATE:
Reason is that I need to start the handling of tests via our new nemo plugin:

e.g.

    nemo.plugins.datadrive.handleTest('xyz.json');

**Comment by grawk** [comment]
Hi Ben.. Sorry for the delay. I feel like we've discussed this issue in another venue, with respect to nemo-mocha-factory simply injecting before/after functions into the scope where it's included, and utilizing the mocha lifecycle features. Closing for now but reopen if this is still an active area of discussion for you
